ALTER TABLE users ADD COLUMN IF NOT EXISTS bio       TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website   TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter   TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS public    BOOLEAN NOT NULL DEFAULT true;
